### ISSUE TITLE
Pylinter does not work on Windows 7

### ISSUE THREAD

**Issue by bhadra** [biermeester/Pylinter#12]
I always get the following error in console when I attempt to run Pylinter with Sublime Text 2 on Windows 7:

Exception in thread Thread-9:
Traceback (most recent call last):
  File ".\threading.py", line 532, in **bootstrap_inner
  File ".\pylinter.py", line 332, in run
  File ".\subprocess.py", line 633, in __init**
  File ".\subprocess.py", line 842, in _execute_child
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

This error is happening with the latest version of Pylinter. It was not happening with the previous version (2012-08-31) of Pylinter.

**Comment by biermeester** [comment]
I just updated to Pylint 0.26 using Pip, but I cannot reproduce the error on Windows 7.

Please make sure your Pylinter settings are correct. If you're not able to resolve this problem, please post your configuration here.

**Comment by bhadra** [comment]
I too use the latest version of Pylint updated through Pip. As soon as run ctrl+alt+z for the file test1.py,  I get the following message on Sublime Text 2 (Windows 7) console:
- PyLinter:  Verbose is True
  - PyLinter:  Running Pylinter on C:\TEMP\test1.py
  - PyLinter:  Current PYTHONPATH is ''
  - PyLinter:  Updated PYTHONPATH is ''
  - PyLinter:  Running command:
    python C:/Python27/Lib/site-packages/pylint/lint.py --output-format=parseable --include-ids=y C:\TEMP\test1.py
    Exception in thread Thread-21:
    Traceback (most recent call last):
    File ".\threading.py", line 532, in **bootstrap_inner
    File ".\pylinter.py", line 332, in run
    File ".\subprocess.py", line 633, in __init**
    File ".\subprocess.py", line 842, in _execute_child
    WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

My Pylinter settings are:

``` javascript

{
    // When versbose is 'true', various messages will be written to the console.
    // values: true or false
    "verbose": true,
    // The full path to the Python executable you want to
    // run Pylint with or simply use 'python'.
    "python_bin": "python",
    // The following paths will be added Pylint's Python path
    "python_path": [

                   ],
    // Optionally set the working directory
    "working_dir": "",
    // Full path to the lint.py module in the pylint package
    "pylint_path": "C:/Python27/Lib/site-packages/pylint/lint.py",
    // Optional full path to a Pylint configuration file
    "pylint_rc": "",
    // Set to true to automtically run Pylint on save
    "run_on_save": false,
    // Ignore Pylint error types. Possible values:
    // "R" : Refactor for a "good practice" metric violation
    // "C" : Convention for coding standard violation
    // "W" : Warning for stylistic problems, or minor programming issues
    // "E" : Error for important programming issues (i.e. most probably bug)
    // "F" : Fatal for errors which prevented further processing
    "ignore": []
}
```

Let me know if you require any additional information.

**Comment by bhadra** [comment]
I uninstalled and then reinstalled Pylinter through Package Control. I continue to get the same error as mentioned in my previous comment.

This error was not occurring with the previous version (2012-08-31) of Pylinter.

**Comment by biermeester** [comment]
Can you try and change the following configuration values:

```
"working_dir": null,
"pylint_rc": null
```

(So, change them to 'null' instead of an empty string.)

**Comment by biermeester** [comment]
Did you manage to resolve the problem?

**Comment by bhadra** [comment]
Sorry about the delayed response. With the configuration values, suggested by you, the problem is resolved. You may close this issue.

**Comment by biermeester** [comment]
Good to hear!
