### ISSUE TITLE
Keybinding for toogling on/off not working

### ISSUE THREAD

**Issue by ispmarin** [biermeester/Pylinter#20]
Sublime Text 2 on Linux, the default Ctrl+Alt+x does not toggle on or off the messages.

**Comment by biermeester** [comment]
I'll have a look on Monday.

**Comment by biermeester** [comment]
It's working for me on Ubuntu with Sublime Text 2, so I'm closing this one. It's probably more of an Linux/Sublime Text issue anyway.
