### ISSUE TITLE
Receiving pylint error after upgrading to pylint 1.0

### ISSUE THREAD

**Issue by thecodenomad** [biermeester/Pylinter#25]
Just upgraded to pylint 1.0 and the latest pylinter. Upon save, I'm now receiving an error:

lint.py: error: no such option: --include-ids

It's trivial, but the error required me to remove pylinter and then re-install.

**Comment by biermeester** [comment]
That's most likely because Pylinter only determines Pylint's version when Sublime Text is first launched. Restart Sublime Text and it should be all good.
