### ISSUE TITLE
Ignored pylint flags are still highlighted

### ISSUE THREAD

**Issue by ijl** [biermeester/Pylinter#31]
If I disable a pylint error/warning/etc flags within a file using `# pylint: disable=<flag>`, and have specified in my `Preferences.sublime-settings` an ignore of `["I0011"]`, with `I0011` being 'Locally disabling' that flag, I still see that line highlighted upon running Pylinter, with `I0011` displayed as the flag.

I expected pylint flags I had ignored to not be highlighted any more. Is there a way to achieve this in the settings?

**Comment by biermeester** [comment]
You have to put it in `"disable": ["I0011"]`. `"ignore"` Is for ignoring classes of messages, like `"R"`, `"C"` etc.

**Comment by biermeester** [comment]
I'm closing this issue, feel free to re-open it if needed.
