### ISSUE TITLE
Pylint 1.0.0: error: no such option: --include-ids

### ISSUE THREAD

**Issue by crogre** [biermeester/Pylinter#36]
As of pylint 1.0.0, the option "--include-ids" is no longer supported. Their docs are not yet updated, but it's mentioned in the ChangeLog (https://bitbucket.org/logilab/pylint/src/656d711815bc70f2f26871bb2a028b3411189710/ChangeLog?at=default)

Edit:
Hmm. It might be that the version is not detected properly on my system - if I force it to 1.0.0 in pylinter.py it works ok.

**Comment by biermeester** [comment]
Pylinter already 'knows' this, but there's a bug in the `Pylinter` code that affects SublimeText 3. An updated version will be committed shortly, which should fix this.

**Comment by biermeester** [comment]
The Pylint version should be detected correctly now, in both SublimeText 2 and 3. Thank you for your feedback. Please feel free to reopen this issue if you problem isn't solved.

**Comment by gimli64** [comment]
I recently encountered the same issue in Sublime Text 2 with pylint 1.0.0 and fixed it by forcing the PYLINT_VERSION in pylinter.py.

**Comment by vladimirnani** [comment]
Had the same error in ST3. But after restart it was gone.

**Comment by biermeester** [comment]
I've updated the Pylint version detection code. Also, please remember that if you're using a Virtualenv, you need to launch SublimeText from that Virtualenv.
