### ISSUE TITLE
Replace icons to more accurate

### ISSUE THREAD

**Issue by 1st** [biermeester/Pylinter#37]
Hello!

Thank you for a good project. It's very helpful for python developers who want to make the best code.

I turned on function `"use_icons": true` and `"disable_outline": true` and se icons in line, where I have errors (or notification icon).

Please make these icons more small and accurate. I think that gray icon will be good for warnings, and red icon for errors that should be fixed asap.

Also I use other plugins that show icons in the line. For example, GitGutter, that shown me what lines have added, removed or changed compared to GIT version. How it will work in case, when I need to see two icons from different plugins at the same time?

Thank you.

**Comment by biermeester** [comment]
I've updated the icons. Their colour now resembles the colours the regions get using the Monokai scheme. Their size has also been slightly reduced.

As for showing 2 icons at the same time on the same line: I don't think that is something Sublime Text can do, so it's out of my hands.

**Comment by 1st** [comment]
Thanks! Looks good. I think that you can make it slightly smaller and more neutral colors.
