### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by anentropic** [biermeester/Pylinter#4]
I installed the package via Package Control, I save a .py file and it complains I need to set path to lint.py ... OK, I set the path and it no longer complains when saving.

But I don't see anything.

I put a deliberate error in the file and save again, still nothing.

pylint from the command line produces output and picks up the error.

cmd+alt+z shows 'PyLinting' and a circle icon briefly in the status bar

I'm assuming it should display some output, maybe highlight the error-ing line?

Any idea what could be wrong?

**Comment by biermeester** [comment]
Pylinter should highlight the lines where it detects something wrong. When you press cmd+alt+c it should show a list of all warnings and errors.

When you open Sublime Text's console with cmd+` you should see any additional output.

Pylinter is still working fine here on Linux and Windows since the 2.0 upgrade. I'll have a look at OSX later today.

Please let me know if you find anything.

**Comment by anentropic** [comment]
cmd+alt+c shortcuts don't do anything for me.  oh, console is ctrl+`

so when I open the ST console I have this error in there:

``````
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./pylinter.py", line 49, in run
  File "./pylinter.py", line 239, in popup_error_list
ValueError: need more than 0 values to unpack```
``````

**Comment by biermeester** [comment]
The fact that cmd+alt+c didn't show anything for you, and the Python exception were both the result of Pylint not finding anything wrong with your code.

I just did a quick commit to resolve the exception.

So, maybe you're just a very clean coder?

**Comment by anentropic** [comment]
I get the same error in the console after putting a deliberate error in the file and saving... (haven't tried updating with your new commit yet)

**Comment by biermeester** [comment]
Open the pylinter.py file and set the PYLINTER_VERBOSE to True, then you should get more output in the console window.

**Comment by anentropic** [comment]
ok, it says:

`- PyLinter:  Running PyLinter on /Users/etc etc`

but then nothing else... not sure if it's actually getting to pylint?  If I copy the file path to terminal window and pylint from there it works 

does the `"python_bin": "python"` in settings file mean it will use the python specified in my project settings (rather than built in ST python) ?

**Comment by biermeester** [comment]
Pylinter always runs an external command in a separate thread, using your local python installation, so the built-in Python is not used.

I've made another commit, with an extra log statement that should output the exact command that Pylinter runs. You might try and copy/paste that into your console and see what happens.

Also, please ignore my previous PYLINTER_VERBOSE comment. Leave it to 'False' and set 'verbose: true' in your configuration file instead.

**Comment by anentropic** [comment]
hmm maybe this is it since my project uses a virtualenv and I have specified the path to the virtualenv python in my project settings (and installed pylint under that python)

ah, now if I give the path to my virtualenv python to pylinter's `python_bin` it works!

I guess it would also work to install pylint under system default python...

I wonder if there's a way to get this to tie more into the per-project python interpreter settings?

**Comment by biermeester** [comment]
Good to hear it works, I'll make an extra note in the documentation file.

And you can define Pylinter configuration on a ST project basis: https://github.com/biermeester/Pylinter#project-settings

Thanks for your feedback!

**Comment by anentropic** [comment]
ah perfect, I am new to Sublime Text and still exploring all the features...
