### ISSUE TITLE
pylint with plugins error: NoSuchChecker

### ISSUE THREAD

**Issue by seedofjoy** [biermeester/Pylinter#40]
When using pylint plugins (for example pylint_django) it will crash on every check. For the proper work pylint must be run by "pylint" command, not lint.py. I solved this problem by specifying "pylint_path" like this: "/usr/local/bin/pylint". Then everything works fine. 
Maybe we should change the way it run for more correct (according to the pylint documentation: by pylint script)?

**Comment by seedofjoy** [comment]
Update: This only works if on sublime text load pylint_path is set to lint.py (pylint package), end after loading pylint_path change to /bin/pylint...

**Comment by biermeester** [comment]
I've added support for Pylint plugins. See the `plugins` setting in the Pylinter configuration file. Just remember that you need to launch SublimeText from the (virtual) environment where you've installed `pylint`/`pylint-django`/`django`.

Also, remember to clear your `pylint_path` settings and that the plugin module is called `pylint_django` with an underscore. Feel free to reopen this issue if you have any problems related to the plugin and Pylinter.
