### ISSUE TITLE
Use sublime API for project settings

### ISSUE THREAD

**Issue by ehuss** [biermeester/Pylinter#6]
It took me a few minutes to figure out why my project-specific settings weren't taking effect.  The code that manually searches the project folders for sublime-project files doesn't handle the case where a sublime-project only includes subfolders (and not the folder the sublime-project file resides in).

I'm not sure if you had a reason for doing it this way.  An alternative would be to do:
sublime.active_window().active_view().settings().get('pylinter')
to get project-specific settings.  This might remove about 30 lines of code.

I can submit a patch if you'd like.

**Comment by biermeester** [comment]
Thanks for the heads up, and a patch would be appreciated!

**Comment by biermeester** [comment]
Thanks for the patch!
