### ISSUE TITLE
Platform-dependent settings

### ISSUE THREAD

**Issue by matthjes** [biermeester/Pylinter#9]
Before I add this to my fork I wanted to ask if its currently possible to define a platform-dependent pylint path. I'm synchronizing my sublimetext settings / packages via dropbox and I'm currently working on Linux and Windows. Pylint is installed in different directories on each platform, so I have to change the path accordingly, but this then gets synchronized via dropbox...and so on. This could be avoided by using a platform-dependent settings file, like it is currently done for the shortcuts.

**Comment by biermeester** [comment]
This can't be done at the moment, but it would be a nice feature to have!

**Comment by matthjes** [comment]
I've also wrote this in another comment for another plugin: it would be nice to have platform- or even host-dependent settings for some plugins / some options (e.g. Pylinters lint path, working path for projects etc.) As I wrote, I'm working on a Linux machine at work and on another Linux machine (or Windows machine) at home and I synchronize everything via Dropbox (very convenient). But some settings that are beyond simple true / false options require a more sophisticated approach, I guess.

It looks like Sublime wants Plugins to use a single configuration file `<Plugin>.sublime-settings`, as we can only use `sublime.load_settings()` with a single base name which (I think) does not get extended by the platform (please correct me if I'm wrong). So either there are three configuration files, one for each platform, or one could write platform (or even host) specific parameters into the configuration files. For example:

```
"pylint_path":
[
  {"platform": "linux", "path": "~/lib/pylint/lint.py"},
  {"platform": "windows", "path": "C:\\Users\\user\libs\pylint\lint.py"}
]
```

or even host dependent:

```
"pylint_path":
[
  {"host": "pc-linux", "path": "~/libs/pylint/lint.py"},
  {"host": "pc-windows1", "path": "C:\\Users\\user\libs\pylint\lint.py"},
  {"host": "pc-windows2", "path": "D:\\MyHome\mylibs\lint.py}
]
```

This way you would have a single configuration file, but still can set up options for all your computers / environments you are working on. What do you think?

**Comment by biermeester** [comment]
I know the problem, since I use Sublime Text on multiple Linux, Windows and OS X machines. 

When I look at your examples, it seems that host specific path configurations would be the most flexible. 

If you're going to make the alteration, please make it so that old configurations will still work. So, check whether 'pylint_path' is a string or a list, and if it's a list, match the correct one using the host name.

**Comment by matthjes** [comment]
Ok, I'll try to make is as general as possible: each option that requires a path either accepts the path or a list of host/path tuples. I'll work on this over the next days.

**Comment by biermeester** [comment]
Nice, good luck! :)

**Comment by matthjes** [comment]
I've added a small function `get_path` that can be called whenever a path option should be read. It simply checks whether the path is a string or a dict with hostname -> path mappings. For example, the pylint_path option can now be given as:

```
"pylint_path": "/path/to/pylint/lint.py"
```

or

```
"pylint_path": 
{
  "pc-linux": "/path/to/pylint/lint.py",
  "pc-windows": "C:\User\users\lib\pylint\lint.py"
}
```

Needs testing on Windows machine, should work under Linux. To get the hostname one could simply open the python console within sublime and enter:

```
import socket
print socket.gethostname()
```

**Comment by matthjes** [comment]
Actually, with a little more work one could modify `get_setting` to allow for all options the choice to either provide a single value or one for each host...which would make working on different machines much more comfortable.

**Comment by biermeester** [comment]
Nice work!
I'm starting to think that host dependent configuration should be (or maybe already is) a feature request for Sublime Text. I'll merge later today. Also, I'll add a dialog warning when the host name is not found, including a message which states the current host name, for convenience.

**Comment by matthjes** [comment]
There is a request, but waaaay down in the list...seems like everyone else found another solution for this. 

It would be nice if Plugins could use other Plugins, so one could create a new Plugin which implements the `get_setting` function...obviously, this would also make it necessary to allow Plugins depend on other Plugins, with the latter getting installed with the former if its not present. Maybe I should start a request...

Anyways, I'll try to modify the `get_setting` to deal with host-dependent options, so at least I can use Pylinter on different machines.

**Comment by matthjes** [comment]
I also want this platform / host dependent settings thing for another plugin (FuzzyFileNav), so I'm kind of crossposting between those two. Here is the link and the latest post. What do you think?

https://github.com/facelessuser/FuzzyFileNav/pull/3#issuecomment-8269748

Both (hosts and OS) should be possible, however, with the limited structure of json it will be a little bit difficult to define the syntax for the configuration files. What I want is: the user either specifies a single value for an option or gives a list (dict) of hosts / os identifiers and a value for each. How should this look like in the settings file? One problem is that a value of an option can be a dict, so one has to differentiate between the dict as value and the dict that holds the hostname / os name to value mapping. 
The other thing to discuss is: given a hostname and an os, what should have precedence? I think the hostname, as this would identify a specific machine.

So an option could look like this:

```
"option": value
```

or

```
"option":
{
    "hosts":
    {
        "pc-windows1": value1,
        "pc-windows2": value2,
        "pc-linux1": value3
    },
    "platform":
    {
        "windows": value4,
        "osx": value5,
        "linux": value6,
    },
    "default": value
}
```

Quite complicated, but I think this is the most flexible way. The first variant (`"option": value) is just a shortcut for

```
"option":
{
    "default": value
}
```

Obviously, values for options that are dicts should not contain the reserved keywords "hosts", "platform", or "default".
The more complex variant includes some fallbacks: if a host id is present that matches the current host, then this option is taken, otherwise the os option is used. If nothing matches, then the default is taken.

What do you think?

**Comment by biermeester** [comment]
Fixed by adding multiconf.
